[package]
name = "xcm-executor-integration-tests"
description = "Integration tests for the XCM Executor (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "1.0.0"
publish = false

[lints]
workspace = true

[dependencies]
codec = { workspace = true, default-features = true }
<<<<<<< HEAD
frame-support.workspace = true
frame-system.workspace = true
frame-system.default-features = true
futures = { workspace = true }
pallet-transaction-payment.workspace = true
pallet-transaction-payment.default-features = true
pallet-xcm.workspace = true
pallet-xcm.default-features = true
polkadot-test-client.workspace = true
polkadot-test-runtime.workspace = true
polkadot-test-service.workspace = true
polkadot-service.workspace = true
polkadot-service.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-runtime.workspace = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
xcm.workspace = true
xcm-executor.workspace = true
xcm-executor.default-features = true
sp-tracing.workspace = true
sp-tracing.default-features = true
sp-core.workspace = true
sp-core.default-features = true
=======
frame-support = { workspace = true }
frame-system = { workspace = true, default-features = true }
futures = { workspace = true }
pallet-transaction-payment = { workspace = true, default-features = true }
pallet-sudo = { workspace = true, default-features = true }
pallet-xcm = { workspace = true, default-features = true }
polkadot-runtime-parachains = { workspace = true, default-features = true }
polkadot-test-client = { workspace = true }
polkadot-test-runtime = { workspace = true }
polkadot-test-service = { workspace = true }
sp-consensus = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-runtime = { workspace = true }
sp-state-machine = { workspace = true, default-features = true }
xcm = { workspace = true }
xcm-executor = { workspace = true, default-features = true }
sp-tracing = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
>>>>>>> c10e25aa (dmp: Check that the para exist before delivering a message (#6604))

[features]
default = ["std"]
std = ["frame-support/std", "frame-system/std", "pallet-sudo/std", "polkadot-runtime-parachains/std", "sp-runtime/std", "xcm/std"]
